taskify/urls.py
from django.contrib import admin
from django.urls import path
from core import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
                  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                  path('signup/', views.SignUpView.as_view(), name='signup'),
                  path('', views.MainView.as_view()),
                  path('todolist/', views.ToDoListView.as_view(), name='todo_list'),
                  path('todolist/<int:pk>/', views.ToDoListDetailView.as_view(), name='todo_list_detail'),
                  path('todotitle/', views.CreateToDoListView.as_view(), name='task_title'),
                  path('creategoal/<int:id>/', views.CreateGoalsView.as_view(), name='create_goal'),
                  path('delete/', views.DeleteGoalView.as_view(), name='delete'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model


class ToDoList(models.Model):
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    goal = models.ManyToManyField('Goals', blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Goals(models.Model):
    PRIORITY_CHOICES = (
        ('low_priority', 'Minor'),
        ('major_priority', 'Major'),
        ('severe_priority', 'Severe'),
    )

    goal = models.CharField(max_length=255)
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='low_priority')
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

core/forms.py
from django import forms

from django.contrib.auth import get_user_model
from core.models import Goals


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if get_user_model().objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')
        return username

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError('Passwords do not match')
        return cleaned_data

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        email = self.cleaned_data.get('email')
        user = get_user_model().objects.create_user(username=username, password=password, email=email)
        return user


class CreateGoalsForm(forms.ModelForm):
    class Meta:
        model = Goals

        fields = ['goal', 'priority']

core/views.py
from django.shortcuts import render
from core.models import Goals, ToDoList
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, FormView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from core.forms import SignUpForm, CreateGoalsForm
from django.http import JsonResponse


class MainView(LoginRequiredMixin, TemplateView):
    template_name = 'main.html'
    login_url = '/login/'


class SignUpView(FormView):
    template_name = 'signup.html'
    form_class = SignUpForm
    success_url = '/login/'

    def form_valid(self, form):
        form.save()
        return super(SignUpView, self).form_valid(form)


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDoList
    template_name = 'todo_list.html'
    context_object_name = 'objects'
    login_url = '/login/'

    def get_queryset(self):
        return ToDoList.objects.filter(user=self.request.user)


class ToDoListDetailView(LoginRequiredMixin, DetailView):
    model = ToDoList
    template_name = 'todo_list_detail.html'
    context_object_name = 'object'
    login_url = '/login/'

    def post(self, request, *args, **kwargs):
        goal_id = request.POST['goal_id']
        goal = Goals.objects.filter(id=goal_id).first()
        if goal.completed:
            goal.completed = False
        else:
            goal.completed = True
        goal.save()
        return JsonResponse({'status': 'success'})


class CreateToDoListView(View):

    def post(self, request, *args, **kwargs):
        title = request.POST['task_title']
        task = ToDoList.objects.create(title=title, user=request.user)
        return JsonResponse({'status': 'success', 'task_id': task.id})


class CreateGoalsView(LoginRequiredMixin, FormView):
    form_class = CreateGoalsForm
    template_name = 'create_goals.html'
    success_url = '.'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo_list'] = ToDoList.objects.filter(id=self.kwargs['id']).first()
        return context

    def form_valid(self, form):
        ToDoList.objects.filter(id=self.kwargs['id']).first().goal.add(form.save())
        return super(CreateGoalsView, self).form_valid(form)


class DeleteGoalView(View):

    def post(self, request, *args, **kwargs):
        goal_id = request.POST['goal_id']
        Goals.objects.filter(id=goal_id).delete()
        return JsonResponse({'status': 'success'})

core/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">
    <title>Taskify</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% block css %}{% endblock css %}
</head>

<body>

<ul class="nav justify-content-center">
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li>
            <a class="nav-link disabled">{{ user.username }}</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
        </li>
    {% endif %}
    <li>
        <a class="nav-link disabled"></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'todo_list' %}">Todo List</a>
    </li>
</ul>

{% block content %}{% endblock content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
{% block js %}{% endblock js %}
</body>
</html>

core/templates/create_goals.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

<style>
    .card {
      margin: 0 auto;
      width: 55%;
    }
    .card-header {
      font-weight: bold;
      font-size: 24px;
    }
    .card-body {
      font-size: 18px;
    }
    .form-control {
      margin-bottom: 10px;
    }
    .btn {
      font-weight: bold;
    }




</style>

{% endblock css %}

{% block content %}

<br>
<h2 class="text-center">{{ todo_list.title }}</h2>
<div class="card mt-5">
    <div class="card-body">
        {% if todo_list.goal.all %}
        <hr>
        {% for goal in todo_list.goal.all %}
        <div class="row">
            {{ goal.id }}
            <span style="width: 75%">{{ goal.goal }}</span>
            <span style="width: 10%">{{ goal.get_priority_display  }}</span>
            <button class="btn btn-danger delete-btn" action="{% url 'delete' %}" data-id="{{ goal.id }}"
                    style="width: 10%">Delete
            </button>
        </div>
        <hr>
        {% endfor %}
        {% else %}
        <h3 class="text-center">You have no goals</h3>
        {% endif %}
    </div>
</div>
<div class="card mt-5">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.goal }}
                {{ form.priority }}
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{% url 'todo_list_detail' todo_list.id %}" class="btn btn-primary">Back</a>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

{% block js %}
<script src="{% static 'js/create-goal.js' %}"></script>
{% endblock js %}

core/templates/login.html
{% extends 'base.html' %}

{% block css %} {% endblock css %}

{% block content %}
<form method="post">
    <div>
        <h2>Login</h2>
        {% csrf_token %}
        <div>
            <p class="card-text">{{form}}</p>
            <button type="submit">Login</button>
        </div>
    </div>
</form>
{% endblock content %}

{% block js %} {% endblock js %}

core/templates/main.html
{% extends 'base.html' %}


{% block content %}


{% endblock content %}

{% block css %} {% endblock css %}

{% block js %} {% endblock js %}

core/templates/signup.html
{% extends 'base.html' %}

{% block js %} {% endblock js %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Sign Up</button>
    </form>
</div>

{% endblock content %}

{% block css %} {% endblock css %}

core/templates/todo_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

<link rel="stylesheet" href="{% static 'css/todo_list.css' %}">

{% endblock css %}

{% block content %}
{% csrf_token %}\\\\

<div class="global-todo-div">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <img src="{% static 'img/img_add.png' %}" class="card-img-top" alt="add">
                </a>

                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Create title of your task list</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form id="title-form" action="{% url 'task_title' %}">
                                    <div class="mb-3">
                                        <label for="task-title" class="col-form-label">Title:</label>
                                        <input type="text" class="form-control" id="task-title">
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary" id="submit-title">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% for object in objects %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">
                <p>{{ object.goal.all.first }}</p>
                <p>{{ object.date }}</p>
                <a href="/todolist/{{ object.id }}/" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/title-todo-list.js' %}"></script>
{% endblock js %}

core/templates/todo_list_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/todo_list_detail.css' %}">
{% endblock css %}

{% block js %}
<script src=" {% static 'js/todo_list_detail.js' %} "></script>
{% endblock js %}

{% block content %}
<br>
{% csrf_token %}
<div class="global-todo-div">
    <div class="row">
        <div class="card">
            <div class="card-body" id="div-card-body" action=".">
                <h3 class="card-title text-center">{{ object.title }}</h3>
                <p class="card-text">
                    {% for goal in object.goal.all %}
                    <p><a href='' class="goal" data-goal_id="{{ goal.id }}" value="{{ goal.completed }}">{{ goal.goal }}</a></p>
                    {% endfor %}
                        <a href="/creategoal/{{ object.id }}/" class="btn btn-primary">Edit ToDo List</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}